name: goal_quest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  dot_navigation_bar: ^1.0.2
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_white.png
    - assets/logo_black.png
    - assets/account_image.png
    - assets/logo_black_horizon.png
    - assets/signup_image.png
    - assets/change_password_image.png

