name: goal_quest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  http: ^0.13.4
  flutter_secure_storage: ^5.0.2
  carousel_slider: ^5.0.0
  dot_navigation_bar: ^1.0.2
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.2.1+1

  intl: ^0.19.0
  percent_indicator: ^4.2.3
  equatable: ^2.0.0
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_white.png
    - assets/logo_black.png
    - assets/account_image.png
    - assets/logo_black_horizon.png
    - assets/signup_image.png
    - assets/change_password_image.png
    - assets/goal_image.png
    - assets/user_image.png

    - assets/ranking.png
    - assets/winner.png


    - assets/slide_1.png
    - assets/slide_2.png
    - assets/slide_3.png
    - assets/slide_4.png

    - assets/mockup/rank_1.png
    - assets/mockup/rank_2.png
    - assets/mockup/rank_3.png



  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-ExtraBold.ttf

